name: Build for Windows

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21.x'

      - name: Set environment variables
        run: |
          echo "GOOS=windows" >> $GITHUB_ENV
          echo "GOARCH=amd64" >> $GITHUB_ENV

      # - name: Run tests
      #   run: go test ./...

      - name: Build application
        run: go build -o getcourse-video-downloader.exe .

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-binary
          path: getcourse-video-downloader.exe
